package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"taskmanager/domain"
	"taskmanager/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	task := &domain.Task{
		Title:       input.Title,
		Description: input.Description,
		Status:      domain.Todo,
	}

	task, err := r.DBRepo.CreateTask(task)

	if err != nil {
		return nil, err
	}

	return ToGraphQL(task), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, input model.UpdateTaskInput) (*model.Task, error) {
	task := &domain.Task{
		ID:          *input.ID,
		Title:       *input.Title,
		Description: input.Description,
	}

	task, err := r.DBRepo.UpdateTask(task)

	if err != nil {
		return nil, err
	}

	return ToGraphQL(task), nil
}

// UpdateTaskStatus is the resolver for the updateTaskStatus field.
func (r *mutationResolver) UpdateTaskStatus(ctx context.Context, input model.UpdateTaskStatusInput) (*model.Task, error) {
	task := &domain.Task{
		ID:     *input.ID,
		Status: domain.Status(*input.Status),
	}

	task, err := r.DBRepo.UpdateTaskStatus(task)

	if err != nil {
		return nil, err
	}

	return ToGraphQL(task), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, input model.DeleteTaskInput) (*model.Task, error) {
	task, err := r.DBRepo.DeleteTask(*input.ID)

	if err != nil {
		return nil, err
	}

	return ToGraphQL(task), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, status *model.Status) ([]*model.Task, error) {
	tasks, err := r.DBRepo.Tasks((*domain.Status)(status))

	if err != nil {
		return nil, err
	}

	return ToArrGraphQL(tasks), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
